---
title: "Colaboración INMEGEN"
author: "Luigui Gallardo Becerra, Adrián Ochoa Leyva"
date: "28.10.2022"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries required
library("colorRamps")
library("ggplot2")
library("reshape")
library("scales")
library("jcolors")
library("grid")
library("RColorBrewer")
library("dplyr")
library("ggpubr")
library("phyloseq")
library("microbiome")
library("vegan")
library("metagMisc")
library("DiagrammeR")
library("microbiomeMarker")
```

## MetaPhlAn3, taxonomía

### Con todas las muestras comparando Positive vs Negative

#### Barplots

```{r, echo=FALSE, warning=FALSE, include=FALSE}
# Input table
biom_file <- "./00_files/metaphlan3_taxonomic_profile_filt_2.biom"

map_file <- "./00_files/metadata_resp.tsv"

biom_otu_tax <- import_biom(biom_file)

metadata <- import_qiime_sample_data(map_file)

physeq <- merge_phyloseq(biom_otu_tax,
                         metadata)

physeq <- normalize(physeq,
                    method = "TSS")

colnames(tax_table(physeq)) <- c("Kingdom",
                                 "Phylum",
                                 "Class",
                                 "Order",
                                 "Family",
                                 "Genus",
                                 "Species")

theme_set(theme_bw())

# Phylum level
phylum <- aggregate_rare(physeq,
                         level = "Phylum",
                         detection = 0.0001,
                         prevalence = 50/100)

barplot_tax_phylum <- plot_bar(phylum,
                               fill = "Phylum") +
facet_wrap(~Response,
           scales = "free_x") +
labs(x = "",
    y = "Relative abundance",
    fill = "Phylum") +
scale_x_discrete(expand = c(0, 0)) +
scale_y_continuous(expand = c(0, 0)) +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))


# Class level
class <- aggregate_rare(physeq,
                         level = "Class",
                         detection = 0.01,
                         prevalence = 50/100)

barplot_tax_class <- plot_bar(class,
                               fill = "Class") +
facet_grid(.~Response,
           scales = "free_x") +
labs(x = "",
    y = "Relative abundance",
    fill = "Class") +
scale_x_discrete(expand = c(0, 0)) +
scale_y_continuous(expand = c(0, 0)) +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))


# Order level
order <- aggregate_rare(physeq,
                         level = "Order",
                         detection = 0.01,
                         prevalence = 50/100)

barplot_tax_order <- plot_bar(order,
                               fill = "Order") +
facet_grid(.~Response,
           scales = "free_x") +
labs(x = "",
    y = "Relative abundance",
    fill = "Order") +
scale_x_discrete(expand = c(0, 0)) +
scale_y_continuous(expand = c(0, 0)) +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))

# Family level
family <- aggregate_rare(physeq,
                         level = "Family",
                         detection = 0.01,
                         prevalence = 50/100)

barplot_tax_family <- plot_bar(family,
                               fill = "Family") +
facet_grid(.~Response,
           scales = "free_x") +
labs(x = "",
    y = "Relative abundance",
    fill = "Family") +
scale_x_discrete(expand = c(0, 0)) +
scale_y_continuous(expand = c(0, 0)) +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))

# Genera level
genera <- aggregate_rare(physeq,
                         level = "Genus",
                         detection = 0,
                         prevalence = 0)

genera.df <- phyloseq_to_df(genera,
                            addtax = FALSE,
                            addtot = FALSE,
                            addmaxrank = FALSE,
                            sorting = "NULL")
               

genera <- aggregate_rare(physeq,
                         level = "Genus",
                         detection = 0.01,
                         prevalence = 50/100)

barplot_tax_genera <- plot_bar(genera,
                               fill = "Genus") +
facet_grid(.~Response,
           scales = "free_x") +
labs(x = "",
    y = "Relative abundance",
    fill = "Genus") +
scale_x_discrete(expand = c(0, 0)) +
scale_y_continuous(expand = c(0, 0)) +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))


# Species level
species <- aggregate_rare(physeq,
                         level = "Species",
                         detection = 0,
                         prevalence = 0)


species.df <- phyloseq_to_df(species,
                             addtax = FALSE,
                             addtot = FALSE,
                             addmaxrank = FALSE,
                             sorting = "NULL")

species <- aggregate_rare(physeq,
                         level = "Species",
                         detection = 0.01,
                         prevalence = 50/100)

barplot_tax_species <- plot_bar(species,
                               fill = "Species") +
facet_grid(.~Response,
           scales = "free_x") +
labs(x = "",
    y = "Relative abundance",
    fill = "Species") +
scale_x_discrete(expand = c(0, 0)) +
scale_y_continuous(expand = c(0, 0)) +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))


```

#### LEfSe

```{r, echo=FALSE, warning=FALSE, include=FALSE}
# Input table
biom_otu_tax <- import_biom(biom_file)

metadata <- import_qiime_sample_data(map_file)

physeq <- merge_phyloseq(biom_otu_tax,
                         metadata)

physeq_lefse <- normalize(physeq,
                          method = "CPM")

colnames(tax_table(physeq_lefse)) <- c("Kingdom",
                                 "Phylum",
                                 "Class",
                                 "Order",
                                 "Family",
                                 "Genus",
                                 "Species")

theme_set(theme_bw())

# LEfSe Phylum
# lefse_phylum <- run_lefse(physeq_lefse,
#                          norm = "none",
#                          taxa_rank = "Phylum",
#                          group = "Response")
#
#plot_lefse_phylum <- plot_ef_bar(lefse_phylum)
#

# LEfSe Class
# lefse_class <- run_lefse(physeq_lefse,
#                           norm = "none",
#                           taxa_rank = "Class",
#                           group = "Response")
# plot_lefse_class <- plot_ef_bar(lefse_class)

# LEfSe Order
# lefse_order <- run_lefse(physeq_lefse,
#                           norm = "none",
#                           taxa_rank = "Order",
#                           group = "Response")
# 
# plot_lefse_order <- plot_ef_bar(lefse_order)

# LEfSe Family
# lefse_family <- run_lefse(physeq_lefse,
#                           norm = "none",
#                           taxa_rank = "Family",
#                           group = "Response")
# 
# plot_lefse_family <- plot_ef_bar(lefse_family)

# LEfSe Genera
# lefse_genera <- run_lefse(physeq_lefse,
#                           norm = "none",
#                           taxa_rank = "Genus",
#                           group = "Response")
# 
# plot_lefse_genera <- plot_ef_bar(lefse_genera)


# LEfSe Species
lefse_species <- run_lefse(physeq_lefse,
                          norm = "none",
                          taxa_rank = "Species",
                          group = "Response")

plot_lefse_species <- plot_ef_bar(lefse_species)

```

```{r, echo = FALSE}
barplot_tax_phylum

# plot_lefse_phylum

barplot_tax_class

# plot_lefse_class

barplot_tax_order

# plot_lefse_order

barplot_tax_family

# plot_lefse_family

barplot_tax_genera

# plot_lefse_genera

barplot_tax_species

plot_lefse_species
```

\newpage

## MetaPhlAn3, diversidad alfa

### Con todas las muestras comparando Positive vs Negative

```{r, echo=FALSE, warning=FALSE, include=FALSE}
# Input table
biom_file <- "./00_files/metaphlan3_taxonomic_profile_filt_2.biom"

map_file <- "./00_files/metadata_resp.tsv"

biom_otu_tax <- import_biom(biom_file)

metadata <- import_qiime_sample_data(map_file)

physeq <- merge_phyloseq(biom_otu_tax,
                         metadata)

rarefied = rarefy_even_depth(physeq,
                             rngseed=1,
                             sample.size=min(sample_sums(physeq)))

theme_set(theme_bw())

# Observed species
alpha_observed <- plot_richness(rarefied,
                                measures = c("Observed"),
                                color = "Response") +
labs(x = "",
    y = "Observed species") +
facet_grid(.~Response,
           scales = "free_x") +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))

alpha_observed_curve <- rarecurve(t(otu_table(rarefied)),
                                 step=50,
                                 cex = 0.5)


# Chao1
alpha_chao1 <- plot_richness(rarefied,
                             measures = c("Chao1"),
                             color = "Response") +
labs(x = "",
    y = "Chao1 Index") +
facet_grid(.~Response,
           scales = "free_x") +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))

alpha_chao1_curve <- rarecurve(t(otu_table(rarefied)),
                                 step=50,
                                 cex = 0.5)


# Shannon
alpha_shannon <- plot_richness(rarefied,
                               measures = c("Shannon"),
                               color = "Response") +
labs(x = "",
    y = "Shannon Index") +
facet_grid(.~Response,
           scales = "free_x") +
theme(axis.text.x = element_text(size = 7,
                                 angle = 90,
                                 vjust = 0.5))

alpha_shannon_curve <- rarecurve(t(otu_table(rarefied)),
                                 step=50,
                                 cex = 0.5)


# All metrics

p_value <- list(c("Negative",
                  "Positive"))

alpha <- plot_richness(rarefied,
              measures = c("Observed",
                           "Chao1",
                           "Shannon"),
              x = "Response",
              color = "Response") +
  geom_boxplot() +
  labs(x = "",
       fill = "") +
  theme(legend.position='none',
        axis.text.x = element_text(size = 7,
                                   angle = 360,
                                   hjust = 0.5)) +
  stat_compare_means(comparisons = p_value,
                     method = "wilcox.test")

alpha

```

```{r, echo = FALSE}
alpha_observed

alpha_chao1

alpha_shannon

alpha
```

\newpage
## MetaPhlAn3, diversidad beta

### Con todas las muestras comparando Positive vs Negative

```{r, echo=FALSE, warning=FALSE, include=FALSE}
# Input table
biom_file <- "./00_files/metaphlan3_taxonomic_profile_filt_2.biom"

map_file <- "./00_files/metadata_resp.tsv"

biom_otu_tax <- import_biom(biom_file)

metadata <- import_qiime_sample_data(map_file)

physeq <- merge_phyloseq(biom_otu_tax,
                         metadata)

rarefied = rarefy_even_depth(physeq,
                             rngseed=1,
                             sample.size=min(sample_sums(physeq)))

theme_set(theme_bw())

# Bray-Curtis PCoA
braycurtis_dist = phyloseq::distance(rarefied,
                                     method="bray")

ordination = ordinate(rarefied,
                      method="PCoA",
                      distance="bray")

# 1 vs 2
beta_braycurtis_1vs2 <- plot_ordination(rarefied,
                ordination,
                color = "Response",
                axes = 1:2,
                label = "sample") +
  labs(title = "Beta diversity, Bray-Curtis") +
  theme(aspect.ratio=1)



# 1 vs 3
beta_braycurtis_1vs3 <- plot_ordination(rarefied,
                ordination,
                color = "Response",
                axes = 1-3,
                label = "sample") +
  labs(title = "Beta diversity, Bray-Curtis") +
  theme(aspect.ratio=1)



# 2 vs 3
beta_braycurtis_2vs3 <- plot_ordination(rarefied,
                ordination,
                color = "Response",
                axes = 2-3,
                label = "sample") +
  labs(title = "Beta diversity, Bray-Curtis") +
  theme(aspect.ratio=1)



# Jaccard PCoA
jaccard_dist = phyloseq::distance(rarefied,
                                  method="jaccard")

ordination = ordinate(rarefied,
                      method="PCoA",
                      distance="jaccard")

# 1 vs 2
beta_jaccard_1vs2 <- plot_ordination(rarefied,
                ordination,
                color = "Response",
                axes = 1:2,
                label = "sample") +
  labs(title = "Beta diversity, Jaccard") +
  theme(aspect.ratio=1)


# 1 vs 3
beta_jaccard_1vs3 <- plot_ordination(rarefied,
                ordination,
                color = "Response",
                axes = 1-3,
                label = "sample") +
  labs(title = "Beta diversity, Jaccard") +
  theme(aspect.ratio=1)



# 2 vs 3
beta_jaccard_2vs3 <- plot_ordination(rarefied,
                ordination,
                color = "Response",
                axes = 2-3,
                label = "sample") +
  labs(title = "Beta diversity, Jaccard") +
  theme(aspect.ratio=1)


```

```{r, echo = FALSE}
beta_braycurtis_1vs2
beta_braycurtis_1vs3
beta_braycurtis_2vs3
```

```{r, echo = FALSE}
beta_jaccard_1vs2
beta_jaccard_1vs3
beta_jaccard_2vs3
```

\newpage

