#!/bin/bash
# Title: script_kneaddata.sh
# Purpose: Kneaddata host removal (human).
# Author: Luigui Gallardo-Becerra (bfllg77@gmail.com)
# Date: 11.01.2022

# Beginning of the script
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL509-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL509-mf_ribopicker_nonrrna_paired_R2.fastq --output RL509-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL511-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL511-mf_ribopicker_nonrrna_paired_R2.fastq --output RL511-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL514-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL514-mf_ribopicker_nonrrna_paired_R2.fastq --output RL514-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL516-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL516-mf_ribopicker_nonrrna_paired_R2.fastq --output RL516-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL518-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL518-mf_ribopicker_nonrrna_paired_R2.fastq --output RL518-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL528-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL528-mf_ribopicker_nonrrna_paired_R2.fastq --output RL528-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL568-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL568-mf_ribopicker_nonrrna_paired_R2.fastq --output RL568-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL569-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL569-mf_ribopicker_nonrrna_paired_R2.fastq --output RL569-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL573-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL573-mf_ribopicker_nonrrna_paired_R2.fastq --output RL573-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL585-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL585-mf_ribopicker_nonrrna_paired_R2.fastq --output RL585-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL591-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL591-mf_ribopicker_nonrrna_paired_R2.fastq --output RL591-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL601-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL601-mf_ribopicker_nonrrna_paired_R2.fastq --output RL601-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL605-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL605-mf_ribopicker_nonrrna_paired_R2.fastq --output RL605-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL606-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL606-mf_ribopicker_nonrrna_paired_R2.fastq --output RL606-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL607-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL607-mf_ribopicker_nonrrna_paired_R2.fastq --output RL607-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL610-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL610-mf_ribopicker_nonrrna_paired_R2.fastq --output RL610-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL613-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL613-mf_ribopicker_nonrrna_paired_R2.fastq --output RL613-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL616-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL616-mf_ribopicker_nonrrna_paired_R2.fastq --output RL616-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL619-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL619-mf_ribopicker_nonrrna_paired_R2.fastq --output RL619-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL621-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL621-mf_ribopicker_nonrrna_paired_R2.fastq --output RL621-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL625-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL625-mf_ribopicker_nonrrna_paired_R2.fastq --output RL625-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL627-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL627-mf_ribopicker_nonrrna_paired_R2.fastq --output RL627-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL628-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL628-mf_ribopicker_nonrrna_paired_R2.fastq --output RL628-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL641-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL641-mf_ribopicker_nonrrna_paired_R2.fastq --output RL641-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL651-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL651-mf_ribopicker_nonrrna_paired_R2.fastq --output RL651-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL654-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL654-mf_ribopicker_nonrrna_paired_R2.fastq --output RL654-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL656-12_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL656-12_ribopicker_nonrrna_paired_R2.fastq --output RL656-12_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL656-3_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL656-3_ribopicker_nonrrna_paired_R2.fastq --output RL656-3_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL656-6_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL656-6_ribopicker_nonrrna_paired_R2.fastq --output RL656-6_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL656-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL656-mf_ribopicker_nonrrna_paired_R2.fastq --output RL656-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL659-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL659-mf_ribopicker_nonrrna_paired_R2.fastq --output RL659-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL663-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL663-mf_ribopicker_nonrrna_paired_R2.fastq --output RL663-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL665-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL665-mf_ribopicker_nonrrna_paired_R2.fastq --output RL665-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL667-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL667-mf_ribopicker_nonrrna_paired_R2.fastq --output RL667-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL668-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL668-mf_ribopicker_nonrrna_paired_R2.fastq --output RL668-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL679-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL679-mf_ribopicker_nonrrna_paired_R2.fastq --output RL679-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL680-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL680-mf_ribopicker_nonrrna_paired_R2.fastq --output RL680-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL682-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL682-mf_ribopicker_nonrrna_paired_R2.fastq --output RL682-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL683-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL683-mf_ribopicker_nonrrna_paired_R2.fastq --output RL683-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL686-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL686-mf_ribopicker_nonrrna_paired_R2.fastq --output RL686-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL691-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL691-mf_ribopicker_nonrrna_paired_R2.fastq --output RL691-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL693-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL693-mf_ribopicker_nonrrna_paired_R2.fastq --output RL693-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL700-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL700-mf_ribopicker_nonrrna_paired_R2.fastq --output RL700-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL703-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL703-mf_ribopicker_nonrrna_paired_R2.fastq --output RL703-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL704-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL704-mf_ribopicker_nonrrna_paired_R2.fastq --output RL704-mf_kead_output &
kneaddata --bypass-trim --bypass-trf --reference-db /home/luigui/databases/kead_databases/ --input ../03_pairing/RL725-mf_ribopicker_nonrrna_paired_R1.fastq --input ../03_pairing/RL725-mf_ribopicker_nonrrna_paired_R2.fastq --output RL725-mf_kead_output &
wait

# The end!